/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ok.restaurante;

import java.awt.Desktop;
import java.awt.Frame;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JTable;

/**
 *
 * @author Luis Fernando
 */
public class Boleta extends javax.swing.JFrame {

    /**
     * Creates new form Boleta
     */
    private DefaultListModel dlm;
    
    public Boleta() {
        dlm = new DefaultListModel();
        Actualizar();
        initComponents();
        Price.setText("S/. "+val);
        jList1.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Solicitar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Price = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        barrita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Solicitar.setBackground(new java.awt.Color(183, 84, 53));
        Solicitar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Concert One", 0, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 250, 243));
        jLabel3.setText("SOLICITAR");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        Solicitar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -20, 220, 100));

        getContentPane().add(Solicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 300, 80));

        Fondo.setBackground(new java.awt.Color(255, 250, 243));
        Fondo.setForeground(new java.awt.Color(0, 0, 0));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\Para_Boleta\\esquina_abajo (1).png")); // NOI18N
        Fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 140, 140));

        jLabel4.setFont(new java.awt.Font("Sriracha", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(183, 84, 53));
        jLabel4.setText("Pago Total:");
        Fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 200, 50));

        jLabel5.setFont(new java.awt.Font("Sriracha", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(183, 84, 53));
        jLabel5.setText("Total Platos:");
        Fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 200, 50));

        Precio.setBackground(new java.awt.Color(255, 204, 204));
        Precio.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Precio.setForeground(new java.awt.Color(205, 198, 197));
        Precio.setText("restauranteLaMar@gmail.com");
        Fondo.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 170, 30));

        jList1.setBackground(new java.awt.Color(255, 250, 243));
        jList1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(183, 84, 53), 1, true));
        jList1.setFont(new java.awt.Font("Sriracha", 0, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(186, 166, 165));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionBackground(new java.awt.Color(183, 84, 53));
        jList1.setSelectionForeground(new java.awt.Color(255, 250, 243));
        jScrollPane1.setViewportView(jList1);

        Fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 270, 180));

        Price.setBackground(new java.awt.Color(255, 204, 204));
        Price.setFont(new java.awt.Font("Sriracha", 0, 30)); // NOI18N
        Price.setForeground(new java.awt.Color(186, 166, 165));
        Price.setText("S/. 0");
        Fondo.add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\Para_Boleta\\esquina1.png")); // NOI18N
        Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -30, -1, -1));

        exit1.setFont(new java.awt.Font("Courier New", 1, 60)); // NOI18N
        exit1.setForeground(new java.awt.Color(255, 0, 0));
        exit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit1.setText("•");
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
        });
        Fondo.add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        exit.setFont(new java.awt.Font("Courier New", 1, 60)); // NOI18N
        exit.setForeground(new java.awt.Color(183, 84, 53));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("•");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        Fondo.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 30));

        barrita.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barritaMouseDragged(evt);
            }
        });
        barrita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barritaMousePressed(evt);
            }
        });
        Fondo.add(barrita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 30));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //PARA BARRITA
    private void barritaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barritaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barritaMousePressed
   
    
    private void barritaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barritaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barritaMouseDragged

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_exitMouseClicked

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
        this.dispose();
        I_principal.Bandera_Desactivar();
    }//GEN-LAST:event_exit1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
        try {
            PrintWriter writer = new PrintWriter("/C:/Users/Luis Fernando/Downloads/boleta.txt", "UTF-8");
            writer.println("===================================================================");
            for(int i=0; i<array.Numero_Elementos();i++)
            {
            writer.println("\t"+array.getNombre(i));
            }
            
            writer.println("\n\n");
            writer.println("===================================================================");
            writer.println("\t"+val);
            writer.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jLabel3MouseClicked
    
    //PARA ACTRUALIZAR LISTA
    public void Actualizar(){
        double precio=0;
        for(int i=0; i<array.Numero_Elementos();i++)
        {
            dlm.addElement(array.getNombre(i));
        }
        
        for(int i=0; i<array.Numero_Elementos();i++)
        {
            precio=precio+array.getPrecio(i);
        }
        
        val = String.valueOf(precio);  
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          
                new Boleta().setVisible(true);
            }
        });
    }

    private String val;
    private static Pedidos array = new Pedidos();
    private int xMouse,yMouse;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Price;
    private javax.swing.JPanel Solicitar;
    private javax.swing.JLabel barrita;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
