package ok.restaurante;

import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author GRUPO 
 */

//PELIGRO: NO TOCAR, SOLO DISEÑO
public class I_principal extends javax.swing.JFrame {

    /**
     * Creates new form I_principal
     */
    public I_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Seleccionar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panel_Imagen = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        busqueda = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Panel_Informacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Panel_Opciones = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Seleccionar.setBackground(new java.awt.Color(183, 84, 53));
        Panel_Seleccionar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Concert One", 0, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECCIONAR");
        Panel_Seleccionar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 320, 80));

        getContentPane().add(Panel_Seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 350, 80));

        Panel_Imagen.setBackground(new java.awt.Color(255, 204, 153));
        Panel_Imagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Flecha_Izquierda.png")); // NOI18N
        Panel_Imagen.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 75, 75));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Flecha_Derecha.png")); // NOI18N
        Panel_Imagen.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 75, 75));

        busqueda.setBackground(new java.awt.Color(255, 250, 243));
        busqueda.setFont(new java.awt.Font("Sriracha", 0, 18)); // NOI18N
        busqueda.setForeground(new java.awt.Color(186, 166, 165));
        busqueda.setText("Búsqueda");
        busqueda.setBorder(null);
        busqueda.setSelectionColor(new java.awt.Color(186, 166, 165));
        busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                busquedaMousePressed(evt);
            }
        });
        Panel_Imagen.add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 190, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Barra_Busqueda.png")); // NOI18N
        Panel_Imagen.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 260, 40));

        getContentPane().add(Panel_Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 580));

        Panel_Informacion.setBackground(new java.awt.Color(255, 250, 243));
        Panel_Informacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sriracha", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(183, 84, 53));
        jLabel2.setText("Precio:");
        Panel_Informacion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 150, 50));

        jLabel3.setFont(new java.awt.Font("Sriracha", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(183, 84, 53));
        jLabel3.setText("Descripción:");
        Panel_Informacion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 200, 50));

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setFont(new java.awt.Font("Sriracha", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(186, 166, 165));
        jLabel4.setText("N°");
        Panel_Informacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 100, 30));

        jLabel6.setFont(new java.awt.Font("Sriracha", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(183, 84, 53));
        jLabel6.setText("Cantidad:");
        Panel_Informacion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 150, 50));

        jLabel7.setBackground(new java.awt.Color(255, 204, 204));
        jLabel7.setFont(new java.awt.Font("Sriracha", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(186, 166, 165));
        jLabel7.setText("linea numero 5-------");
        Panel_Informacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 230, 30));

        jLabel8.setBackground(new java.awt.Color(255, 204, 204));
        jLabel8.setFont(new java.awt.Font("Sriracha", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(186, 166, 165));
        jLabel8.setText("N°");
        Panel_Informacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 100, 30));

        jLabel9.setBackground(new java.awt.Color(255, 204, 204));
        jLabel9.setFont(new java.awt.Font("Sriracha", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(186, 166, 165));
        jLabel9.setText("linea numero 1-------");
        Panel_Informacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 230, 30));

        jLabel10.setBackground(new java.awt.Color(255, 204, 204));
        jLabel10.setFont(new java.awt.Font("Sriracha", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(186, 166, 165));
        jLabel10.setText("linea numero 2-------");
        Panel_Informacion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 230, 30));

        jLabel11.setBackground(new java.awt.Color(255, 204, 204));
        jLabel11.setFont(new java.awt.Font("Sriracha", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(186, 166, 165));
        jLabel11.setText("linea numero 3-------");
        Panel_Informacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 230, 30));

        jLabel12.setBackground(new java.awt.Color(255, 204, 204));
        jLabel12.setFont(new java.awt.Font("Sriracha", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(186, 166, 165));
        jLabel12.setText("linea numero 4-------");
        Panel_Informacion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 230, 30));

        getContentPane().add(Panel_Informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 340, 580));

        Panel_Opciones.setBackground(new java.awt.Color(183, 84, 53));
        Panel_Opciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton4_normal.png")); // NOI18N
        jToggleButton1.setBorder(null);
        jToggleButton1.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton4_sombreado.png")); // NOI18N
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton4_presionado.png")); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        Panel_Opciones.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 75, 75));

        jToggleButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton1_normal.png")); // NOI18N
        jToggleButton2.setBorder(null);
        jToggleButton2.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton1_sombreado.png")); // NOI18N
        jToggleButton2.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton1_presionado.png")); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        Panel_Opciones.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 75, 75));

        jToggleButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton2_normal.png")); // NOI18N
        jToggleButton3.setBorder(null);
        jToggleButton3.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton2_sombreado.png")); // NOI18N
        jToggleButton3.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton2_presionado.png")); // NOI18N
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        Panel_Opciones.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 75, 75));

        jToggleButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton3_normal.png")); // NOI18N
        jToggleButton4.setBorder(null);
        jToggleButton4.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton3_sombreado.png")); // NOI18N
        jToggleButton4.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton3_presionado.png")); // NOI18N
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        Panel_Opciones.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 75, 75));

        getContentPane().add(Panel_Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1300, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void busquedaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busquedaMousePressed
        busqueda.setText("");
    }//GEN-LAST:event_busquedaMousePressed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new I_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Imagen;
    private javax.swing.JPanel Panel_Informacion;
    private javax.swing.JPanel Panel_Opciones;
    private javax.swing.JPanel Panel_Seleccionar;
    private javax.swing.JTextField busqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
