package ok.restaurante;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import static ok.restaurante.Base_Datos.platos;

/**
 *
 * @author GRUPO 
 */

//PELIGRO: NO TOCAR, SOLO DISEÑO
public class I_principal extends javax.swing.JFrame {

    /**
     * Creates new form I_principal
     */
    public I_principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Imagen = new javax.swing.JPanel();
        Boton_Adelante = new javax.swing.JLabel();
        Boton_Atras = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        busqueda = new javax.swing.JTextField();
        Imagen_Fondo = new javax.swing.JLabel();
        Panel_Informacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Panel_Seleccionar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panel_Opciones = new javax.swing.JPanel();
        Boton_platos = new javax.swing.JToggleButton();
        Boton_informacion = new javax.swing.JToggleButton();
        Boton_bebidas = new javax.swing.JToggleButton();
        Boton_postres = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Imagen.setBackground(new java.awt.Color(255, 204, 153));
        Panel_Imagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Adelante.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Flecha_Derecha.png")); // NOI18N
        Boton_Adelante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Adelante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_AdelanteMouseClicked(evt);
            }
        });
        Panel_Imagen.add(Boton_Adelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 75, 75));

        Boton_Atras.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Flecha_Izquierda.png")); // NOI18N
        Boton_Atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_AtrasMouseClicked(evt);
            }
        });
        Panel_Imagen.add(Boton_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 75, 75));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Barra_Busqueda.png")); // NOI18N
        Panel_Imagen.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 260, 40));

        busqueda.setBackground(new java.awt.Color(255, 250, 243));
        busqueda.setFont(new java.awt.Font("Sriracha", 0, 18)); // NOI18N
        busqueda.setForeground(new java.awt.Color(186, 166, 165));
        busqueda.setText("Búsqueda");
        busqueda.setBorder(null);
        busqueda.setSelectionColor(new java.awt.Color(186, 166, 165));
        busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                busquedaMousePressed(evt);
            }
        });
        Panel_Imagen.add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 190, 40));

        Imagen_Fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\Platos\\ceviche.jpg")); // NOI18N
        Panel_Imagen.add(Imagen_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 580));

        getContentPane().add(Panel_Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 580));

        Panel_Informacion.setBackground(new java.awt.Color(255, 250, 243));
        Panel_Informacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sriracha", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(183, 84, 53));
        jLabel2.setText("Precio:");
        Panel_Informacion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 150, 50));

        jLabel3.setFont(new java.awt.Font("Sriracha", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(183, 84, 53));
        jLabel3.setText("Descripción:");
        Panel_Informacion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 200, 50));

        Precio.setBackground(new java.awt.Color(255, 204, 204));
        Precio.setFont(new java.awt.Font("Sriracha", 0, 30)); // NOI18N
        Precio.setForeground(new java.awt.Color(186, 166, 165));
        Precio.setText("S/. 28");
        Panel_Informacion.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 130, 30));

        Nombre.setFont(new java.awt.Font("Sriracha", 0, 30)); // NOI18N
        Nombre.setForeground(new java.awt.Color(183, 84, 53));
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("CEVICHE");
        Panel_Informacion.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 340, 50));

        jLabel7.setBackground(new java.awt.Color(255, 204, 204));
        jLabel7.setFont(new java.awt.Font("Sriracha", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(186, 166, 165));
        jLabel7.setText("linea numero 5-------");
        Panel_Informacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 230, 30));

        jLabel8.setBackground(new java.awt.Color(255, 204, 204));
        jLabel8.setFont(new java.awt.Font("Sriracha", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(186, 166, 165));
        jLabel8.setText("N°");
        Panel_Informacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 100, 30));

        jLabel9.setBackground(new java.awt.Color(255, 204, 204));
        jLabel9.setFont(new java.awt.Font("Sriracha", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(186, 166, 165));
        jLabel9.setText("linea numero 1-------");
        Panel_Informacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 230, 30));

        jLabel10.setBackground(new java.awt.Color(255, 204, 204));
        jLabel10.setFont(new java.awt.Font("Sriracha", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(186, 166, 165));
        jLabel10.setText("linea numero 2-------");
        Panel_Informacion.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 230, 30));

        jLabel11.setBackground(new java.awt.Color(255, 204, 204));
        jLabel11.setFont(new java.awt.Font("Sriracha", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(186, 166, 165));
        jLabel11.setText("linea numero 3-------");
        Panel_Informacion.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 230, 30));

        jLabel12.setBackground(new java.awt.Color(255, 204, 204));
        jLabel12.setFont(new java.awt.Font("Sriracha", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(186, 166, 165));
        jLabel12.setText("linea numero 4-------");
        Panel_Informacion.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 230, 30));

        jLabel15.setFont(new java.awt.Font("Sriracha", 0, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(183, 84, 53));
        jLabel15.setText("Cantidad:");
        Panel_Informacion.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, 50));

        Panel_Seleccionar.setBackground(new java.awt.Color(183, 84, 53));
        Panel_Seleccionar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Concert One", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECCIONAR");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Seleccionar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 290, 80));

        Panel_Informacion.add(Panel_Seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 80));

        getContentPane().add(Panel_Informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 340, 580));

        Panel_Opciones.setBackground(new java.awt.Color(183, 84, 53));
        Panel_Opciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_platos.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton4_normal.png")); // NOI18N
        Boton_platos.setBorder(null);
        Boton_platos.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton4_sombreado.png")); // NOI18N
        Boton_platos.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton4_presionado.png")); // NOI18N
        Boton_platos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_platosActionPerformed(evt);
            }
        });
        Panel_Opciones.add(Boton_platos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 75, 75));

        Boton_informacion.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton1_normal.png")); // NOI18N
        Boton_informacion.setBorder(null);
        Boton_informacion.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton1_sombreado.png")); // NOI18N
        Boton_informacion.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton1_presionado.png")); // NOI18N
        Boton_informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_informacionActionPerformed(evt);
            }
        });
        Panel_Opciones.add(Boton_informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 75, 75));

        Boton_bebidas.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton2_normal.png")); // NOI18N
        Boton_bebidas.setBorder(null);
        Boton_bebidas.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton2_sombreado.png")); // NOI18N
        Boton_bebidas.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton2_presionado.png")); // NOI18N
        Boton_bebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_bebidasActionPerformed(evt);
            }
        });
        Panel_Opciones.add(Boton_bebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 75, 75));

        Boton_postres.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton3_normal.png")); // NOI18N
        Boton_postres.setBorder(null);
        Boton_postres.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton3_sombreado.png")); // NOI18N
        Boton_postres.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\imagenes\\Boton3_presionado.png")); // NOI18N
        Boton_postres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_postresActionPerformed(evt);
            }
        });
        Panel_Opciones.add(Boton_postres, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 75, 75));

        getContentPane().add(Panel_Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1300, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_platosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_platosActionPerformed
          if(Boton_platos.isSelected()){
              Boton_bebidas.isSelected();
              Boton_postres.isSelected();
          }
          else{
              Boton_bebidas.setEnabled(true);
              Boton_informacion.setEnabled(true);
              Boton_postres.setEnabled(true);
          }
    }//GEN-LAST:event_Boton_platosActionPerformed

    private void Boton_informacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_informacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_informacionActionPerformed

    private void Boton_bebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_bebidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_bebidasActionPerformed

    private void Boton_postresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_postresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_postresActionPerformed

    private void busquedaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busquedaMousePressed
        busqueda.setText("");
    }//GEN-LAST:event_busquedaMousePressed

    private void Boton_AdelanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_AdelanteMouseClicked
        contador_imagenes++;
        if(contador_imagenes>53){
            contador_imagenes=0;
            Imagen_Fondo.setIcon(arreglo.getImagen(contador_imagenes));
            Nombre.setText(arreglo.getNombre(contador_imagenes));
            Precio.setText("S/. "+String.valueOf(arreglo.getPrecio(contador_imagenes)));
        }
        else{
            Imagen_Fondo.setIcon(arreglo.getImagen(contador_imagenes));
            Nombre.setText(arreglo.getNombre(contador_imagenes));
            Precio.setText("S/. "+String.valueOf(arreglo.getPrecio(contador_imagenes)));
        }
    }//GEN-LAST:event_Boton_AdelanteMouseClicked

    private void Boton_AtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_AtrasMouseClicked
        contador_imagenes--;
              
        if(contador_imagenes<0){
            contador_imagenes=53;
            Imagen_Fondo.setIcon(arreglo.getImagen(contador_imagenes));
            Nombre.setText(arreglo.getNombre(contador_imagenes));
            Precio.setText("S/. "+String.valueOf(arreglo.getPrecio(contador_imagenes)));
        }
        else{
            Imagen_Fondo.setIcon(arreglo.getImagen(contador_imagenes));
            Nombre.setText(arreglo.getNombre(contador_imagenes));
            Precio.setText("S/. "+String.valueOf(arreglo.getPrecio(contador_imagenes)));
        }
        
    }//GEN-LAST:event_Boton_AtrasMouseClicked
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new I_principal().setVisible(true);
            }
        });
    }
    
    
    
    private int contador_imagenes = 0;
    private Base_Datos arreglo = new Base_Datos();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Boton_Adelante;
    private javax.swing.JLabel Boton_Atras;
    private javax.swing.JToggleButton Boton_bebidas;
    private javax.swing.JToggleButton Boton_informacion;
    private javax.swing.JToggleButton Boton_platos;
    private javax.swing.JToggleButton Boton_postres;
    private javax.swing.JLabel Imagen_Fondo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel Panel_Imagen;
    private javax.swing.JPanel Panel_Informacion;
    private javax.swing.JPanel Panel_Opciones;
    private javax.swing.JPanel Panel_Seleccionar;
    private javax.swing.JLabel Precio;
    private javax.swing.JTextField busqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}

class Eventos implements KeyListener{

    @Override
    public void keyTyped(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        //int cpd = e.getKeyCode();
        //System.out.println(cpd);
    }

    @Override
    public void keyPressed(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void keyReleased(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
}
