/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ok.restaurante;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.TimerTask;
import javax.swing.Timer;

/**
 *
 * @author Luis Fernando
 */
public class TimeChange extends javax.swing.JFrame {

    public Timer tiempo;
   
    public TimeChange() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        tiempo = new Timer(5500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                dispose();
                I_principal Ventana1 = new I_principal();
                Ventana1.setVisible(true);
                Ventana1.setLocationRelativeTo(null);
                Ventana1.setResizable(false);
            }        
        });
        tiempo.setRepeats(false);
        tiempo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("...");
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel1KeyReleased(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 330, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Fernando\\Documents\\Unamba\\Ciclo 4\\Desarrolllo de Software\\SYSTERANT\\RESTAURANTE\\src\\main\\java\\Gif\\loadingfood.gif")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.util.Timer temp= new java.util.Timer();
        
        TimeChange p= new TimeChange();
        p.setVisible(true);
       
        TimerTask carga= new TimerTask() {
            @Override
            public void run() {
               String CargaGeneral;
               int carga= (int) (Math.random()*5);
               
                switch (carga){
                
                    case 0:
                        CargaGeneral="Cargando...";
                        p.jLabel1.setText(CargaGeneral);
                       break;
                    case 1:
                        CargaGeneral="Cargando Pedido...";
                        p.jLabel1.setText(CargaGeneral);
                        
                       break;   
                    case 2:
                        CargaGeneral="Cargando Platos...";
                        p.jLabel1.setText(CargaGeneral);
                        
                       break;   
                     case 3:
                        CargaGeneral="Cargando Postres...";
                        p.jLabel1.setText(CargaGeneral);
                        
                       break;
                    case 4:
                        CargaGeneral="Cargando Bebidas...";
                        p.jLabel1.setText(CargaGeneral);
                        
                       break;
                }           
            }
        };
        
        temp.scheduleAtFixedRate(carga, 1000, 800);
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
